create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
create table copsboot_user (auth_server_id uuid, id uuid not null, email varchar(255), mobile_token varchar(255), primary key (id));
create table report (date_time timestamp(6) with time zone, id uuid not null, reporter_id uuid, description varchar(255), primary key (id));
