version: '3'
services:
  db:
    image: 'postgres:16.0'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: my-postgres-db-pwd
      POSTGRES_DB: copsbootdb
  identity:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: "start-dev --import-realm"
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin-secret
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
